- hosts: all
  become: true
  tasks:
    - name: install package
      yum:
        name: "{{package_name}}"
        state: latest
    - name: Copy index.html file
      copy: 
        src: index.html
        dest: /var/www/html/index.html
    - name: start service
      service: 
        name: "{{package_name}}"
        state: started
    - name: print package name
      debug:
        msg: "{{package_name}}"

