---
services:
 mydb:
  environment:
    MYSQL_ROOT_PASSWORD: ashokit
  image: "mysql:5"
 mysite:
  image: wordpress
  links:
    - "mydb:mysql"
  ports:
    - "5050:80"
version: "3"




version: "3"
services:
  boot-app:
    image: sb-rest-api
    ports:
    - "8080:8080"
    depends_on:
    -  mysql-db
  mysql-db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=ashokit
      - MYSQL_DATABASE=bootdb


