---
    apiVersion: v1
    kind: Service
    metadata:
      name: k8s-boot-demo-service-preprod
    spec:
      type: NodePort
      selector:
        version: v2
      ports:
      - port: 8080
        targetPort: 8080
        nodePort: 30092
...